:chapter-label:
:icons: font
:lang: en
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: highlightjs
:toc: left
:toclevels: 1

= RubyFriendlyError image:https://img.shields.io/badge/ruby-2.4.4-cc342d.svg["ruby 2.4.4", link="https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-4-4-released/"] image:https://img.shields.io/badge/ruby-2.5.1-cc342d.svg["ruby 2.5.1", link="https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-5-1-released/"]

image:https://travis-ci.org/isuke/ruby_friendly_error.svg?branch=master["Build Status", link="https://travis-ci.org/isuke/ruby_friendly_error"]

== Installation and Usage

Add this line to your application's Gemfile:

```ruby
gem 'ruby_friendly_error'
```

```sh
$ bundle exec ruby_friendly_error your.rb
```

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to https://rubygems.org[rubygems.org].

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/isuke/ruby_friendly_error. This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the http://contributor-covenant.org[Contributor Covenant] code of conduct.

== License

The gem is available as open source under the terms of the https://opensource.org/licenses/MIT[MIT License].

== Code of Conduct

Everyone interacting in the RubyFriendlyError project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the [code of conduct](https://github.com/isuke/ruby_friendly_error/blob/master/CODE_OF_CONDUCT.adoc).
